image: node:6.9.4

pipelines:
  branches:
    master:
      - step:
          name: Deploy to Heroku
          script:
            - npm install
            - npm test
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
