reaction:
  name: 'Reactions'
  type: 'reaction'
  sended: 'Enviadas'
  received: 'Recebidas'
reply:
  name: 'Replies'
  type: 'reply'
  sended: 'Enviados'
  received: 'Recebidos'
message:
  name: 'Mensagens'
  type: 'message'
  sended: 'Enviadas'
  received: 'Recebidas'
