limits:
  daily: 40
messages:
  send: 1
threads:
  send: 2
  receive: 1
reactions:
  atena: 0.1
  send: 1
  receive:
    positive: 2
    negative: -1
github:
  issue: 1
  review: 1
  pull_request: 1
  merged_pull_request: 3
inactive:
  mindays: 14
  value: -1
